In [10]:
import tensorflow as tf
from tensorflow import keras
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [11]:
print(tf.__version__)
print(keras.__version__)

2.7.0
2.7.0


In [12]:
dataset = pd.read_csv('train.csv')
print(dataset.columns)
dataset.head(10)

Index(['battery_power', 'blue', 'clock_speed', 'dual_sim', 'fc', 'four_g',
       'int_memory', 'm_dep', 'mobile_wt', 'n_cores', 'pc', 'px_height',
       'px_width', 'ram', 'sc_h', 'sc_w', 'talk_time', 'three_g',
       'touch_screen', 'wifi', 'price_range'],
      dtype='object')


battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  m_dep  \
0            842     0          2.2         0   1       0           7    0.6   
1           1021     1          0.5         1   0       1          53    0.7   
2            563     1          0.5         1   2       1          41    0.9   
3            615     1          2.5         0   0       0          10    0.8   
4           1821     1          1.2         0  13       1          44    0.6   
5           1859     0          0.5         1   3       0          22    0.7   
6           1821     0          1.7         0   4       1          10    0.8   
7           1954     0          0.5         1   0       0          24    0.8   
8           1445     1          0.5         0   0       0          53    0.7   
9            509     1          0.6         1   2       1           9    0.1   

   mobile_wt  n_cores  ...  px_height  px_width   ram  sc_h  sc_w  talk_time  \
0        188        2  ...         20       756  2549     9     7         19   
1        136        3  ...        905      1988  2631    17     3          7   
2        145        5  ...       1263      1716  2603    11     2          9   
3        131        6  ...       1216      1786  2769    16     8         11   
4        141        2  ...       1208      1212  1411     8     2         15   
5        164        1  ...       1004      1654  1067    17     1         10   
6        139        8  ...        381      1018  3220    13     8         18   
7        187        4  ...        512      1149   700    16     3          5   
8        174        7  ...        386       836  1099    17     1         20   
9         93        5  ...       1137      1224   513    19    10         12   

   three_g  touch_screen  wifi  price_range  
0        0             0     1            1  
1        1             1     0            2  
2        1             1     0            2  
3        1             0     0            2  
4        1             1     0            1  
5        1             0     0            1  
6        1             0     1            3  
7        1             1     1            0  
8        1             0     0            0  
9        1             0     0            0  

[10 rows x 21 columns]

In [13]:
X = dataset.iloc[:,:20].values
y = dataset.iloc[:,20:21].values
print(X[0])
print(y[:10])
sc = StandardScaler()
X = sc.fit_transform(X)
print('Normalized data:')
print(X[0])
ohe = OneHotEncoder()
y = ohe.fit_transform(y).toarray()
print('One hot encoded array:')
print(y[:10])
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.2,random_state = 0)


[8.420e+02 0.000e+00 2.200e+00 0.000e+00 1.000e+00 0.000e+00 7.000e+00
 6.000e-01 1.880e+02 2.000e+00 2.000e+00 2.000e+01 7.560e+02 2.549e+03
 9.000e+00 7.000e+00 1.900e+01 0.000e+00 0.000e+00 1.000e+00]
[[1]
 [2]
 [2]
 [2]
 [1]
 [1]
 [3]
 [0]
 [0]
 [0]]
Normalized data:
[-0.90259726 -0.9900495   0.83077942 -1.01918398 -0.76249466 -1.04396559
 -1.38064353  0.34073951  1.34924881 -1.10197128 -1.3057501  -1.40894856
 -1.14678403  0.39170341 -0.78498329  0.2831028   1.46249332 -1.78686097
 -1.00601811  0.98609664]
One hot encoded array:
[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 1.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]]


In [16]:
model = keras.Sequential()
model.add(keras.layers.Dense(16, input_dim=20, activation='relu'))
model.add(keras.layers.Dense(12, activation='relu'))
model.add(keras.layers.Dense(4, activation='softmax'))
model.compile(loss='categorical_crossentropy', optimizer='Adam', metrics=['accuracy'])
model.fit(X_train, y_train, epochs=200, batch_size=80)
model.summary()

Epoch 1/200
20/20 [==============================] - 1s 3ms/step - loss: 1.5800 - accuracy: 0.2350
Epoch 2/200
20/20 [==============================] - 0s 2ms/step - loss: 1.4774 - accuracy: 0.2550
Epoch 3/200
20/20 [==============================] - 0s 2ms/step - loss: 1.4124 - accuracy: 0.2750
Epoch 4/200
20/20 [==============================] - 0s 2ms/step - loss: 1.3662 - accuracy: 0.3069
Epoch 5/200
20/20 [==============================] - 0s 2ms/step - loss: 1.3280 - accuracy: 0.3363
Epoch 6/200
20/20 [==============================] - 0s 2ms/step - loss: 1.2909 - accuracy: 0.3650
Epoch 7/200
20/20 [==============================] - 0s 2ms/step - loss: 1.2514 - accuracy: 0.3913
Epoch 8/200
20/20 [==============================] - 0s 2ms/step - loss: 1.2073 - accuracy: 0.4100
Epoch 9/200
20/20 [==============================] - 0s 2ms/step - loss: 1.1563 - accuracy: 0.4469
Epoch 10/200
20/20 [==============================] - 0s 3ms/step - loss: 1.0991 - accuracy: 0.4975
Epoch 11/

In [17]:
predications = model.predict(X_test)
y_pred = list()
for i in range(len(predications)):
    y_pred.append(np.argmax(predications[i]))

ytest = list()
for i in range(len(y_test)):
    ytest.append(np.argmax(y_test[i]))

print('Accuracy is:', accuracy_score(ytest, y_pred)*100)
print('confusion_matrix:-\n \n ',confusion_matrix(ytest,y_pred))
print("Confusion matrix :-\n \n",classification_report(ytest, y_pred))

Accuracy is: 93.0
