In [1]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt

In [2]:
dsT = pd.read_csv('train.csv')
print("Training dataset detials")
dsT.head()


Training dataset detials


battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  m_dep  \
0            842     0          2.2         0   1       0           7    0.6   
1           1021     1          0.5         1   0       1          53    0.7   
2            563     1          0.5         1   2       1          41    0.9   
3            615     1          2.5         0   0       0          10    0.8   
4           1821     1          1.2         0  13       1          44    0.6   

   mobile_wt  n_cores  ...  px_height  px_width   ram  sc_h  sc_w  talk_time  \
0        188        2  ...         20       756  2549     9     7         19   
1        136        3  ...        905      1988  2631    17     3          7   
2        145        5  ...       1263      1716  2603    11     2          9   
3        131        6  ...       1216      1786  2769    16     8         11   
4        141        2  ...       1208      1212  1411     8     2         15   

   three_g  touch_screen  wifi  price_range  
0        0             0     1            1  
1        1             1     0            2  
2        1             1     0            2  
3        1             0     0            2  
4        1             1     0            1  

[5 rows x 21 columns]

In [3]:
dsT.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   battery_power  2000 non-null   int64  
 1   blue           2000 non-null   int64  
 2   clock_speed    2000 non-null   float64
 3   dual_sim       2000 non-null   int64  
 4   fc             2000 non-null   int64  
 5   four_g         2000 non-null   int64  
 6   int_memory     2000 non-null   int64  
 7   m_dep          2000 non-null   float64
 8   mobile_wt      2000 non-null   int64  
 9   n_cores        2000 non-null   int64  
 10  pc             2000 non-null   int64  
 11  px_height      2000 non-null   int64  
 12  px_width       2000 non-null   int64  
 13  ram            2000 non-null   int64  
 14  sc_h           2000 non-null   int64  
 15  sc_w           2000 non-null   int64  
 16  talk_time      2000 non-null   int64  
 17  three_g        2000 non-null   int64  
 18  touch_sc

In [4]:
print(dsT['price_range'].value_counts())

3    500
2    500
1    500
0    500
Name: price_range, dtype: int64


In [5]:
# Get features and target
x = dsT.iloc[:,0:20].values  
y =dsT.iloc[:, 20].values 


In [6]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.45)

In [7]:
from sklearn.preprocessing import StandardScaler  
sc = StandardScaler()  
x_train = sc.fit_transform(x_train)  
x_test = sc.transform(x_test) 


In [8]:
from sklearn.svm import SVC
#svclassifier = SVC(kernel='poly', degree=4)
#svclassifier = SVC(kernel='linear',C=0.1)
svclassifier = SVC(kernel='rbf',C=0.2)
#svclassifier = SVC(kernel='sigmoid')
svclassifier.fit(x_train, y_train)

SVC(C=0.2)

In [9]:
y_pred = svclassifier.predict(x_test)

In [10]:
from sklearn.metrics import classification_report, confusion_matrix
ConfMat=confusion_matrix(y_test, y_pred)
print(ConfMat)


[[166  55   0   0]
 [ 24 192   1   0]
 [  0 131  49  74]
 [  0   3  12 193]]


In [11]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.87      0.75      0.81       221
           1       0.50      0.88      0.64       217
           2       0.79      0.19      0.31       254
           3       0.72      0.93      0.81       208

    accuracy                           0.67       900
   macro avg       0.72      0.69      0.64       900
weighted avg       0.73      0.67      0.63       900



In [12]:
from sklearn.metrics import accuracy_score

print(' accuracy:')
print((accuracy_score(y_test, y_pred)))

 accuracy:
0.6666666666666666
